### ISSUE TITLE
Moar Control

### ISSUE THREAD

**Issue by ManuSuresh256** [lapoozza/lapzbot#15]
plej add Volume control 
also shuffle, queueing, etc

**Comment by sharktrace** [comment]
( ._.)
...
- Discord already has a per-user volume control, there's no reason to implement it again.
- There already is an open issue for queueing.
- I don't see the point of having shuffle and queue together. Wouldn't you be pissed if you had to stand in line for something and the order randomly changed after every person?

**Comment by JewelMahanta** [comment]
Yeah I think **shuffle** and **volume control** is not required. Queuing is already an open issue in #13 . Closing this thread.
